### ISSUE TITLE
Symbolization of Python eval function doesn't work

### ISSUE THREAD

**Issue by danielpacak** [open-telemetry/opentelemetry-ebpf-profiler#711]
I have this very simple Python Flask app that uses the eval() built-in function. However, the eval() function itself is not symbolized properly, even though surrounding stack frames look legit.

I can provide a minimal reproducible app repo for tests, but before doing that I just wanted to confirm if this is a well known issue related to Python versions and distributions or I'm doing something stupid in my backend? So far I've seen that it's broken for libc and musl-based builds. In particular, I run my tests with CPython 3.10 and 3.13. For both I've got the following stack frame:

```
Instrumentation: cpython, Function: , File: , Line: 0, Column: 0
```

Unless, it's just the issue with my backend and iterating over locations in the OTel profile signal 🤔 ?

``` python
from flask import Flask

app = Flask(__name__)

@app.route("/python/eval")
def python_eval():
    out = eval("__import__('subprocess').getoutput('uname -a')")
    return {"out": str(out)}

if __name__ == "__main__":
    app.run()
```

```
Instrumentation: native: Function: 0x10f008, File: libpython3.10.so.1.0
Instrumentation: native: Function: 0x1175b5, File: libpython3.10.so.1.0
Instrumentation: cpython, Function: communicate, File: /usr/local/lib/python3.10/subprocess.py, Line: 1128, Column: 0
Instrumentation: cpython, Function: run, File: /usr/local/lib/python3.10/subprocess.py, Line: 491, Column: 0
Instrumentation: cpython, Function: check_output, File: /usr/local/lib/python3.10/subprocess.py, Line: 408, Column: 0
Instrumentation: cpython, Function: getstatusoutput, File: /usr/local/lib/python3.10/subprocess.py, Line: 626, Column: 0
Instrumentation: cpython, Function: getoutput, File: /usr/local/lib/python3.10/subprocess.py, Line: 645, Column: 0
Instrumentation: cpython, Function: , File: , Line: 0, Column: 0
Instrumentation: cpython, Function: python_eval, File: /app/app.py, Line: 76, Column: 0
Instrumentation: cpython, Function: dispatch_request, File: /app/.venv/lib/python3.10/site-packages/flask/app.py, Line: 889, Column: 0
Instrumentation: cpython, Function: full_dispatch_request, File: /app/.venv/lib/python3.10/site-packages/flask/app.py, Line: 911, Column: 0
Instrumentation: cpython, Function: wsgi_app, File: /app/.venv/lib/python3.10/site-packages/flask/app.py, Line: 1506, Column: 0
Instrumentation: cpython, Function: __call__, File: /app/.venv/lib/python3.10/site-packages/flask/app.py, Line: 1536, Column: 0
Instrumentation: cpython, Function: execute, File: /app/.venv/lib/python3.10/site-packages/werkzeug/serving.py, Line: 331, Column: 0
Instrumentation: cpython, Function: run_wsgi, File: /app/.venv/lib/python3.10/site-packages/werkzeug/serving.py, Line: 249, Column: 0
Instrumentation: cpython, Function: handle_one_request, File: /usr/local/lib/python3.10/http/server.py, Line: 401, Column: 0
Instrumentation: cpython, Function: handle, File: /usr/local/lib/python3.10/http/server.py, Line: 431, Column: 0
Instrumentation: cpython, Function: handle, File: /app/.venv/lib/python3.10/site-packages/werkzeug/serving.py, Line: 398, Column: 0
Instrumentation: cpython, Function: __init__, File: /usr/local/lib/python3.10/socketserver.py, Line: 742, Column: 0
```

**Comment by fabled** [comment]
It is very likely that this is a bug. We have seen earlier similar unsymbolized Python frames, but were not sure what causes it. I believe `eval` was tested originally, but some Python internal might have changed since, so adding a test case for `eval` sounds like a good idea.

**Comment by danielpacak** [comment]
@fabled I'll give it a shot to figure why eval is not symbolized. I'll start with adding some tests as you suggested.

**Comment by florianl** [comment]
@danielpacak the merge of https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/837 should resolve this issue.

In the initial comment of https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/837 in the Before picture, one can also spot these invalid `cpython, Function: , File: , Line: 0, Column: 0` frames and these frames are resolved when applying the change (see After picture).

I also tested it locally just now again, and it works as expected.

<img width="1868" height="1856" alt="Image" src="https://github.com/user-attachments/assets/9420fdbb-d036-42f4-ac07-75061e7d2648" />

Can you confirm this with your tests so that we could close this issue?

**Comment by danielpacak** [comment]
Thanks @florianl for the heads up and great news! I'll test ASAP and confirm.

**Comment by danielpacak** [comment]
I can check also for 3.13 but for 3.9 and 3.10 it still doesn't work, i.e. we see `0x0000` instead of `eval`.

<img width="758" height="875" alt="Image" src="https://github.com/user-attachments/assets/92db1bd2-68ae-42dd-a87b-d9075b795d78" />

<img width="797" height="832" alt="Image" src="https://github.com/user-attachments/assets/e8b024a5-8d50-4bfd-8031-d7b3f6983557" />

**Comment by florianl** [comment]
@danielpacak could you provide a coredump to investigate this?

**Comment by danielpacak** [comment]
> [@danielpacak](https://github.com/danielpacak) could you provide a coredump to investigate this?

Sorry for a late reply @florianl. Indeed, the best would be to catch the coredump and figure why the stack frame for eval() is not symbolized. I'll add a simple Python script test source and a corresponding coredump so we can investigate further.

**Comment by danielpacak** [comment]
I think my original description of this issue was inaccurate and confusing. The eval function is properly backtraced and is represetned as a native frame, not cpython unwind type. For example, I did check manually Python 3.11 and there is the native frame that corresponds to the `builtin_eval` symbol.

``` python
#!/usr/bin/env python
# Driving an eval'd expression in a tight loop keeps such a frame on
# the stack so the profiler is likely to sample it.

import os

def driver():
    while True:
        eval("sum(i * i for i in range(100000))")

print(f"pid={os.getpid()}", flush=True)
driver()
```

```
--------------- New Resource Profile --------------
  process.pid: 86452
  process.executable.path: /home/dpacak/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/bin/python3.11
  process.executable.name: python3.11
------------------- New Profile -------------------
  ProfileID: 00000000000000000000000000000000
  Time: 2026-05-25 20:38:51.639783526 +0000 UTC
  Duration: 5353990083
  PeriodType: [cpu, nanoseconds]
  Period: 50000000
  Dropped attributes count: 0
  SampleType: samples
------------------- New Sample --------------------
  Timestamp[0]: 1779741532689796088 (2026-05-25 22:38:52.689796088 +0200 CEST)
  thread.name: python3.11
  thread.id: 86452
  cpu.logical_number: 5
---------------------------------------------------
Instrumentation: cpython, Function: <genexpr>, File: <string>, Line: 1, Column: 0
Instrumentation: native: Function: 0x38ae98, File: python3.11 (_PyEval_EvalFrameDefault)
Instrumentation: native: Function: 0x31ecc4, File: python3.11 (gen_iternext)
Instrumentation: native: Function: 0x1eeef3, File: python3.11 (PyIter_Next)
Instrumentation: native: Function: 0x4ce0f9, File: python3.11 (builtin_sum)
Instrumentation: native: Function: 0x34198a, File: python3.11 (cfunction_vectorcall_FASTCALL_KEYWORDS)
Instrumentation: cpython, Function: <module>, File: <string>, Line: 1, Column: 0
Instrumentation: native: Function: 0x3c21f4, File: python3.11 (_PyEval_EvalFrameDefault)
Instrumentation: native: Function: 0x388935, File: python3.11 (_PyEval_Vector)
Instrumentation: native: Function: 0x4ffd75, File: python3.11 (run_mod)
Instrumentation: native: Function: 0x4cce3d, File: python3.11 (builtin_eval)
Instrumentation: cpython, Function: driver, File: /home/dpacak/go/src/github.com/danielpacak/opentelemetry-ebpf-profiler/tools/coredump/testsources/python/eval.py, Line: 14, Column: 0
Instrumentation: cpython, Function: <module>, File: /home/dpacak/go/src/github.com/danielpacak/opentelemetry-ebpf-profiler/tools/coredump/testsources/python/eval.py, Line: 17, Column: 0
Instrumentation: native: Function: 0x3c5bb1, File: python3.11 (_PyEval_EvalFrameDefault)
Instrumentation: native: Function: 0x388935, File: python3.11 (_PyEval_Vector)
Instrumentation: native: Function: 0x4ffd75, File: python3.11 (run_mod)
Instrumentation: native: Function: 0x25364b, File: python3.11 (pyrun_file)
Instrumentation: native: Function: 0x253152, File: python3.11 (_PyRun_SimpleFileObject)
Instrumentation: native: Function: 0x252b65, File: python3.11 (_PyRun_AnyFileObject)
Instrumentation: native: Function: 0x25cf57, File: python3.11 (pymain_run_file_obj)
Instrumentation: native: Function: 0x25ca64, File: python3.11 (pymain_run_file)
Instrumentation: native: Function: 0x50afd8, File: python3.11 (Py_RunMain)
Instrumentation: native: Function: 0x50b71c, File: python3.11 (pymain_main)
Instrumentation: native: Function: 0x435a1b, File: python3.11 (main)
Instrumentation: native: Function: 0x2a1c9, File: libc.so.6
Instrumentation: native: Function: 0x2a28a, File: libc.so.6
Instrumentation: native: Function: 0x43592c, File: python3.11 (_start)
------------------- End Sample --------------------
```

I'm using uv to manage Python versions:

```
uv python install 3.11
```

Run eval.py forcing uv to use only managed version of Python, not the system default. Why? The managed versions usually have debug symbols, whereas system default is usually stripped.

```
uv run --python-preference only-managed --python 3.11 eval.py
```

``` console
$ uv python find --python-preference only-managed 3.11
/home/dpacak/.local/share/uv/python/cpython-3.11-linux-x86_64-gnu/bin/python3.11
```

``` console
$ nm "$(uv python find --python-preference only-managed 3.11)" 2>/dev/null | grep ' builtin_eval'
00000000004ccca0 t builtin_eval
0000000000c3a180 r builtin_eval__doc__
```

``` console
$ addr2line -fCe "$(uv python find --python-preference only-managed 3.11)" 0x4cce3d                                                                                   
builtin_eval
??:?
```

**Comment by danielpacak** [comment]
@florianl  @fabled with above comment, we can either close the issue or still add Python test sources to exercise eval and some other built-in functions. WDYT? Happy to add such example if you think it will be useful.
